In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import sqlite3

In [2]:
db=sqlite3.connect("Capstone_project.db")
cursor=db.cursor()

In [3]:
df=pd.read_csv(r'C:\Users\hp\OneDrive\Desktop\data sets\capstoneprojectdatasets\Table_1.csv')
df

,Hotel,City,location,Number_of_reviews,User_rating,Star_rating,Review_score
0,Earls Court East Serviced Apartments,London,Kensington and Chelsea,881,8.1,4,Very Good
1,The Langham London,London,Westminster Borough,1544,9.2,5,Superb
2,City View Hotel - Roman Road Market,London,Tower Hamlets,410,4.2,2,Pleasant
3,Gresham Hotel Bloomsbury,London,Camden,1993,4.4,0,Pleasant
4,"Maldron Hotel Finsbury Park, London",London,Islington,236,8.5,4,Very Good
...,...,...,...,...,...,...,...
1616,Kensington Place Property,Toronto,Downtown Toronto,56,7.4,2,Pleasant
1617,Casa Queen Hotel,Toronto,Leslieville,39,8.5,0,Pleasant
1618,Yonge Suites Furnished Apartments,Toronto,Downtown Toronto,379,9.2,0,Pleasant
1619,Residence Inn by Marriott Toronto Airport,Toronto,Etobicoke,251,8.2,3,Good
1620,Residence Inn by Marriott Toronto Downtown / E...,Toronto,Downtown Toronto,1290,8.2,4,Very Good

In [9]:
# loading the Table1.csv file into sql database 
df.to_sql('DataTable_1',db)

1621

In [10]:
df1=pd.read_csv(r'C:\Users\hp\OneDrive\Desktop\data sets\capstoneprojectdatasets\table_2.csv')
df1

,Hotel,Free_wifi,Family_rooms,Non_Smoking_Rooms,Restaurant,Bar,Heating,Lift,Breakfast_Cuisine1_Continental,Breakfast_Cuisine2_Vegetarian,Breakfast_Cuisine3_American
0,Earls Court East Serviced Apartments,yes,yes,yes,yes,yes,yes,yes,No,No,No
1,The Langham London,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes
2,City View Hotel - Roman Road Market,yes,No,yes,yes,yes,yes,yes,No,No,No
3,Gresham Hotel Bloomsbury,No,No,yes,yes,yes,yes,yes,No,No,No
4,"Maldron Hotel Finsbury Park, London",yes,yes,yes,yes,yes,yes,yes,yes,yes,No
...,...,...,...,...,...,...,...,...,...,...,...
1616,Kensington Place Property,yes,yes,yes,No,No,No,No,No,No,No
1617,Casa Queen Hotel,No,yes,yes,No,No,yes,No,No,No,No
1618,Yonge Suites Furnished Apartments,yes,yes,No,yes,yes,yes,yes,No,No,No
1619,Residence Inn by Marriott Toronto Airport,yes,No,yes,yes,No,yes,yes,yes,No,yes
1620,Residence Inn by Marriott Toronto Downtown / E...,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes

In [11]:
# loading the Table2.csv file into sql database 
df1.to_sql('DataTable_2',db)

1621

In [12]:
df2=pd.read_csv(r'C:\Users\hp\OneDrive\Desktop\data sets\capstoneprojectdatasets\Table_3.csv')
df2

,Hotel,Room_Type,Double_Bed,Single_Bed,Price_in_INR
0,Earls Court East Serviced Apartments,Double Room,yes,No,13022
1,The Langham London,Standard Room,No,yes,73237
2,City View Hotel - Roman Road Market,Standard Room,No,yes,5682
3,Gresham Hotel Bloomsbury,Double Room,yes,No,9567
4,"Maldron Hotel Finsbury Park, London",Double Room,yes,No,16082
...,...,...,...,...,...
1616,Kensington Place Property,Double Room,yes,No,14357
1617,Casa Queen Hotel,Standard Room,yes,No,24648
1618,Yonge Suites Furnished Apartments,Deluxe Room,yes,No,25880
1619,Residence Inn by Marriott Toronto Airport,Double Room,yes,No,18800
1620,Residence Inn by Marriott Toronto Downtown / E...,Deluxe Room,yes,No,46769

In [13]:
# loading the Table3.csv file into sql database 
df2.to_sql('DataTable_3',db)

1621

# Write the SQL queries :

### Table 1

#### 1)  Write a query to give  details of hotels, city is Sydney and  User ratings is more than 5.

In [14]:
SNo=[]
Hotel=[]
City=[]
Location=[]
reviews=[]
star=[]
userrating=[]

In [15]:
sql="SELECT * FROM DataTable_1 WHERE City='Sydney' AND 'User_rating'> 5"
result = cursor.execute(sql)
rows = result.fetchall()
for row in rows:
    SNo.append(row[0])
    Hotel.append(row[1])
    City.append(row[2])
    Location.append(row[3])
    reviews.append(row[4])
    star.append(row[6])
    userrating.append(row[5])

In [16]:
DF=pd.DataFrame({'S.no':SNo,'Hotel':Hotel,"City":City,'Location':Location,'Total Reviews':reviews,"Star Rating":star,'User Rating':userrating})
DF

,S.no,Hotel,City,Location,Total Reviews,Star Rating,User Rating
0,925,Moxy Sydney Airport,Sydney,Mascot,52,4,8.9
1,926,ibis Styles Sydney Central,Sydney,Sydney CBD,5642,3,7.5
2,927,CKS Sydney Airport Hotel,Sydney,Sydney CBD,2899,5,7.2
3,928,The Tank Stream Sydney,Sydney,Sydney CBD,2182,4,8.5
4,929,Regents Sydney,Sydney,Potts Point,402,4,7.9
...,...,...,...,...,...,...,...
145,1070,Citadines Walker North Sydney,Sydney,North Sydney,30,4,8.9
146,1071,Campsie Hotel,Sydney,Campsie,402,3,5.7
147,1072,Little National Hotel Sydney,Sydney,Sydney CBD,4285,5,9.2
148,1073,Mercure Sydney Martin Place,Sydney,Sydney CBD,2104,4,7.8
149,1074,Ace Hotel Sydney,Sydney,Sydney CBD,1193,5,8.8

####   2)   Write a query  to find the location with the most reviews.

In [17]:
result=cursor.execute("SELECT City,Location,Number_of_reviews FROM DataTable_1 ORDER BY Number_of_reviews DESC ")
for _ in result:
    print(_)

('Dubai', 'Jumeirah Beach Residence', 38531)
('London', 'Westminster Borough', 27914)
('London', 'Lambeth', 21514)
('Manchester', 'Manchester City Centre', 20965)
('Berlin', 'Mitte', 19648)
('Berlin', 'Friedrichshain-Kreuzberg', 19182)
('London', 'Tower Hamlets', 18252)
('London', 'Tower Hamlets', 17419)
('Berlin', 'Mitte', 16943)
('Dubai', 'Barsha Heights (Tecom) ', 16677)
('Berlin', 'Tempelhof-Schöneberg', 16453)
('Dubai', 'Garhoud', 15867)
('Dubai', 'Garhoud', 15682)
('Dubai', 'Garhoud', 13928)
('Berlin', 'Mitte', 13245)
('Berlin', 'Mitte', 13132)
('Berlin', 'Mitte', 12657)
('Manchester', 'Manchester City Centre', 12548)
('Paris', '18th arr.', 12469)
('Manchester', 'Manchester City Centre', 12328)
('Manchester', 'Manchester City Centre', 12318)
('Berlin', 'Mitte', 12286)
('Berlin', 'Mitte', 12187)
('Manchester', 'Manchester City Centre', 12094)
('London', 'Tower Hamlets', 11825)
('Sydney', 'Sydney CBD', 11563)
('London', 'Westminster Borough', 11415)
('London', 'Islington', 11172)
('Toronto', 'Financial District', 10947)
('Manchester', 'Manchester City Centre', 10751)
('London', 'Lambeth', 10714)
('Dubai', 'Garhoud', 10613)
('Berlin', 'Friedrichshain-Kreuzberg', 10550)
('London', 'Westminster Borough', 10488)
('Dubai', 'Deira', 10326)
('Berlin', 'Mitte', 10319)
('Berlin', 'Friedrichshain-Kreuzberg', 10246)
('Manchester', 'Manchester City Centre', 10137)
('Birmingham', 'Birmingham City Centre', 10137)
('Dubai', 'Garhoud', 10116)
('Sydney', 'Sydney CBD', 9932)
('Melbourne', 'Melbourne CBD', 9927)
('Paris', '12th arr.', 9843)
('Berlin', 'Mitte', 9815)
('Berlin', 'Mitte', 9795)
('Dubai', 'Deira', 9773)
('Berlin', 'Mitte', 9705)
('London', 'Kensington and Chelsea', 9678)
('Dubai', 'Bur Dubai', 9640)
('Dubai', 'Business Bay', 9566)
('Dubai', 'Bur Dubai', 9553)
('Manchester', 'Manchester City Centre', 9495)
('Manchester', 'Manchester City Centre', 9460)
('London', 'Islington', 9168)
('Berlin', 'Charlottenburg-Wilmersdorf', 9156)
('Tokyo', 'Minato', 9148)
('Sydney', 'Sydney CBD', 9097)
('Berlin', 'Mitte', 8845)
('London', 'Kensington and Chelsea', 8773)
('Berlin', 'Tempelhof-Schöneberg', 8536)
('Manchester', 'Manchester City Centre', 8524)
('Berlin', 'Mitte', 8467)
('Berlin', 'Mitte', 8466)
('London', 'Kensington and Chelsea', 8446)
('Melbourne', 'Melbourne CBD', 8372)
('Birmingham', 'The Westside', 8351)
('Dubai', 'Barsha Heights (Tecom) ', 8318)
('Manchester', 'Salford', 8261)
('London', 'Southwark', 8172)
('Dubai', 'Discovery Gardens', 8131)
('Dubai', 'Bur Dubai', 8117)
('Melbourne', 'Melbourne CBD', 8116)
('Dubai', 'Trade Centre', 8113)
('Toronto', 'The Village', 8084)
('Berlin', 'Mitte', 8047)
('Manchester', 'Manchester City Centre', 8045)
('Dubai', 'Downtown Dubai', 7970)
('Manchester', 'Manchester City Centre', 7866)
('Paris', '12th arr.', 7806)
('Dubai', 'Business Bay', 7791)
('Paris', '12th arr.', 7774)
('Manchester', 'Manchester City Centre', 7763)
('Manchester', 'Manchester City Centre', 7744)
('Berlin', 'Mitte', 7743)
('Birmingham', 'The Westside', 7735)
('New Delhi', 'South West Delhi', 7700)
('Dubai', 'Al Barsha', 7677)
('Dubai', 'Bur Dubai', 7670)
('Dubai', 'Bur Dubai', 7670)
('Berlin', 'Mitte', 7643)
('Dubai', 'Deira', 7638)
('Kuala Lumpur', 'Chow Kit', 7623)
('London', 'City of London', 7535)
('Berlin', 'Charlottenburg-Wilmersdorf', 7512)
('Berlin', 'Charlottenburg-Wilmersdorf', 7512)
('Berlin', 'Friedrichshain-Kreuzberg', 7498)
('Sydney', 'Sydney CBD', 7494)
('Dubai', 'Bur Dubai', 7434)
('Kuala Lumpur', 'Bangsar South', 7371)
('Melbourne', 'Southbank', 7370)
('Dubai', 'Business Bay', 7344)
('Melbourne', 'Southbank', 7325)
('Dubai', 'Barsha Heights (Tecom) ', 7321)
('Paris', '14th arr.', 7316)
('Melbourne', 'Melbourne CBD', 7312)
('Manchester', 'Manchester City Centre', 7293)
('London', 'Lambeth', 7244)
('Dubai', 'Beach & Coast', 7215)
('Berlin', 'Charlottenburg-Wilmersdorf', 7128)
('London', 'Westminster Borough', 7095)
('Berlin', 'Mitte', 7026)
('Berlin', 'Mitte', 6981)
('Berlin', 'Mitte', 6974)
('Sydney', 'Sydney CBD', 6939)
('Manchester', 'Manchester City Centre', 6915)
('Dubai', 'Deira', 6840)
('Dubai', 'Deira', 6752)
('Berlin', 'Mitte', 6733)
('Melbourne', 'Melbourne CBD', 6718)
('Dubai', 'Al Wasl', 6668)
('Dubai', 'Barsha Heights (Tecom) ', 6614)
('Melbourne', 'Melbourne CBD', 6596)
('Birmingham', 'The Westside', 6578)
('Manchester', 'Manchester City Centre', 6540)
('Dubai', 'Downtown Dubai', 6450)
('London', 'Camden', 6415)
('Manchester', 'Manchester City Centre', 6405)
('Berlin', 'Mitte', 6402)
('Paris', '12th arr.', 6391)
('Tokyo', 'Shinagawa Ward', 6391)
('Manchester', 'Manchester City Centre', 6384)
('Manchester', 'Manchester City Centre', 6384)
('Manchester', 'Manchester City Centre', 6307)
('Berlin', 'Mitte', 6304)
('Dubai', 'Garhoud', 6300)
('Birmingham', 'The Westside', 6276)
('New Delhi', 'Mahipalpur', 6247)
('Manchester', 'Manchester City Centre', 6206)
('Kuala Lumpur', 'Chow Kit', 6184)
('Manchester', 'Salford', 6184)
('Birmingham', 'Birmingham Shopping District', 6182)
('Manchester', 'Manchester City Centre', 6146)
('Melbourne', 'Docklands', 6131)
('Dubai', 'Business Bay', 6115)
('Berlin', 'Charlottenburg-Wilmersdorf', 6112)
('Sydney', 'Sydney CBD', 6074)
('London', 'Hammersmith and Fulham', 6018)
('Toronto', 'Downtown Toronto', 6016)
('Berlin', 'Lichtenberg', 6005)
('Sydney', 'Sydney CBD', 5971)
('Dubai', 'Al Barsha', 5957)
('London', 'Tower Hamlets', 5916)
('Manchester', 'Salford', 5915)
('New Delhi', 'South West Delhi', 5908)
('London', 'Southwark', 5900)
('Berlin', 'Friedrichshain-Kreuzberg', 5891)
('Dubai', 'Jumeirah Beach Residence', 5890)
('Dubai', 'Jumeirah Beach Residence', 5890)
('Berlin', 'Charlottenburg-Wilmersdorf', 5884)
('New Delhi', 'South West Delhi', 5866)
('Birmingham', 'Birmingham Shopping District', 5851)
('Kuala Lumpur', 'Sri Hartamas', 5839)
('Paris', '15th arr.', 5832)
('Kuala Lumpur', 'Chow Kit', 5812)
('Tokyo', 'Minato', 5798)
('Dubai', 'Garhoud', 5755)
('Berlin', 'Mitte', 5747)
('Melbourne', 'Melbourne CBD', 5722)
('Sydney', 'Sydney CBD', 5711)
('Manchester', 'Manchester City Centre', 5695)
('London', 'Lambeth', 5682)
('London', 'Camden', 5653)
('Berlin', 'Lichtenberg', 5649)
('Sydney', 'Sydney CBD', 5642)
('Manchester', 'Manchester City Centre', 5637)
('Sydney', 'Sydney CBD', 5636)
('Dubai', 'International City ', 5616)
('Dubai', 'Al Barsha', 5599)
('Sydney', 'Sydney CBD', 5564)
('London', 'Tower Hamlets', 5545)
('Manchester', 'Manchester City Centre', 5533)
('Birmingham', 'Birmingham Shopping District', 5470)
('Melbourne', 'Southbank', 5467)
('Melbourne', 'Southbank', 5467)
('Dubai', 'Deira', 5431)
('Paris', '10th arr.', 5385)
('Dubai', 'Al Barsha', 5371)
('Sydney', 'North Sydney', 5357)
('Dubai', 'Deira', 5323)
('Manchester', 'Manchester City Centre', 5312)
('Berlin', 'Mitte', 5309)
('Melbourne', 'Melbourne CBD', 5288)
('Berlin', 'Mitte', 5280)
('Sydney', 'Sydney CBD', 5274)
('Berlin', 'Charlottenburg-Wilmersdorf', 5268)
('London', 'Greenwich', 5223)
('London', 'Westminster Borough', 5207)
('Berlin', 'Friedrichshain-Kreuzberg', 5201)
('Paris', '13th arr.', 5189)
('Melbourne', 'Melbourne CBD', 5165)
('Berlin', 'Charlottenburg-Wilmersdorf', 5160)
('Berlin', 'Friedrichshain-Kreuzberg', 5138)
('Berlin', 'Mitte', 5126)
('Berlin', 'Mitte', 5117)
('London', 'Westminster Borough', 5103)
('Birmingham', 'Birmingham Shopping District', 5089)
('Berlin', 'Charlottenburg-Wilmersdorf', 5056)
('Toronto', 'Downtown Toronto', 5042)
('Tokyo', 'Minato', 5032)
('Melbourne', 'Melbourne CBD', 5010)
('Birmingham', 'Jewellery Quarter', 4968)
('Dubai', 'Deira', 4944)
('Berlin', 'Mitte', 4944)
('Birmingham', 'Eastside', 4909)
('London', 'Westminster Borough', 4905)
('Birmingham', 'Birmingham City Centre', 4886)
('Melbourne', 'Melbourne CBD', 4886)
('London', 'Kensington and Chelsea', 4862)
('Manchester', 'Manchester City Centre', 4853)
('Berlin', 'Charlottenburg', 4810)
('Melbourne', 'Southbank', 4775)
('Dubai', 'Trade Centre', 4766)
('Dubai', 'Dubai World Central', 4759)
('London', 'Newham', 4710)
('Manchester', 'Manchester City Centre', 4695)
('London', 'Westminster Borough', 4671)
('Paris', '11th arr.', 4670)
('Berlin', 'Mitte', 4645)
('London', 'Westminster Borough', 4640)
('Dubai', 'Al Qusais', 4629)
('Berlin', 'Tempelhof-Schöneberg', 4624)
('Birmingham', 'Birmingham Shopping District', 4621)
('Manchester', 'Manchester City Centre', 4606)
('Tokyo', 'Sumida Ward', 4602)
('Berlin', 'Mitte', 4591)
('London', 'Newham', 4577)
('Berlin', 'Mitte', 4577)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 4576)
('London', 'Tower Hamlets', 4568)
('Melbourne', 'Melbourne CBD', 4532)
('Birmingham', 'Jewellery Quarter', 4529)
('Kuala Lumpur', 'Brickfields', 4522)
('Dubai', 'Dubai Investment Park', 4512)
('Manchester', 'Salford', 4471)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 4469)
('London', 'Greenwich', 4448)
('Paris', '10th arr.', 4430)
('Manchester', 'Manchester City Centre', 4408)
('Dubai', 'Beach & Coast', 4379)
('Berlin', 'Mitte', 4378)
('Manchester', 'Salford', 4372)
('Manchester', 'Salford', 4372)
('Sydney', 'Sydney CBD', 4364)
('Melbourne', 'Melbourne CBD', 4357)
('Melbourne', 'Melbourne CBD', 4357)
('Dubai', 'Dubai Festival City', 4356)
('Dubai', 'Garhoud', 4356)
('Birmingham', 'Birmingham City Centre', 4356)
('Manchester', 'Salford', 4349)
('Berlin', 'Friedrichshain-Kreuzberg', 4339)
('Sydney', 'Sydney CBD', 4338)
('Berlin', 'Mitte', 4331)
('Tokyo', 'Chuo Ward', 4321)
('London', 'Hackney', 4309)
('Sydney', 'Sydney CBD', 4285)
('Dubai', 'Bur Dubai', 4282)
('Melbourne', 'Melbourne CBD', 4272)
('Melbourne', 'Melbourne CBD', 4265)
('London', 'Westminster Borough', 4252)
('Tokyo', 'Shinagawa Ward', 4251)
('London', 'Hammersmith and Fulham', 4247)
('New Delhi', 'South West Delhi', 4231)
('Berlin', 'Charlottenburg-Wilmersdorf', 4222)
('Sydney', 'Mascot', 4210)
('Paris', '13th arr.', 4210)
('Melbourne', 'Melbourne CBD', 4200)
('Melbourne', 'Southbank', 4200)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 4180)
('Manchester', 'Manchester City Centre', 4180)
('Berlin', 'Charlottenburg-Wilmersdorf', 4173)
('Birmingham', 'Edgbaston', 4163)
('Sydney', 'Sydney CBD', 4162)
('Birmingham', 'The Westside', 4158)
('Manchester', 'Manchester City Centre', 4153)
('Melbourne', 'Southbank', 4146)
('Sydney', 'Sydney CBD', 4145)
('Berlin', 'Mitte', 4140)
('Birmingham', 'The Westside', 4131)
('Sydney', 'Mascot', 4128)
('Tokyo', 'Ota Ward', 4118)
('Birmingham', 'Birmingham City Centre', 4106)
('London', 'Southwark', 4089)
('London', 'Newham', 4073)
('Berlin', 'Tempelhof-Schöneberg', 4070)
('London', 'Westminster Borough', 4062)
('Paris', '12th arr.', 4050)
('Manchester', 'Manchester City Centre', 4043)
('Paris', '10th arr.', 4039)
('Kuala Lumpur', 'KL Sentral Train Station', 4029)
('Sydney', 'Mascot', 4022)
('Melbourne', 'Melbourne CBD', 4008)
('Dubai', 'Dubai Festival City', 4007)
('Paris', '15th arr.', 4000)
('Sydney', 'Sydney CBD', 3987)
('Tokyo', 'Koto Ward', 3982)
('Berlin', 'Mitte', 3977)
('Dubai', 'Dubai Silicon Oasis', 3970)
('Toronto', 'The Village', 3969)
('Manchester', 'Manchester City Centre', 3961)
('Berlin', 'Tempelhof-Schöneberg', 3942)
('Berlin', 'Neukölln', 3929)
('Birmingham', 'The Westside', 3912)
('Dubai', 'Bur Dubai', 3911)
('London', 'Camden', 3904)
('Melbourne', 'Carlton', 3900)
('Melbourne', 'Southbank', 3887)
('London', 'Greenwich', 3885)
('Tokyo', 'Shinjuku Ward', 3885)
('Sydney', 'Sydney CBD', 3883)
('Sydney', 'Sydney CBD', 3880)
('Manchester', 'Salford', 3849)
('Birmingham', 'Business District', 3845)
('Manchester', 'Salford', 3837)
('Berlin', 'Mitte', 3831)
('London', 'Newham', 3824)
('Manchester', 'Manchester City Centre', 3802)
('Berlin', 'Mitte', 3798)
('London', 'Wandsworth', 3794)
('Paris', '11th arr.', 3775)
('Kuala Lumpur', 'Bukit Bintang', 3772)
('Kuala Lumpur', 'Bukit Bintang', 3771)
('Berlin', 'Tempelhof-Schöneberg', 3768)
('Berlin', 'Tempelhof-Schöneberg', 3767)
('Sydney', 'Sydney CBD', 3755)
('Melbourne', 'Melbourne CBD', 3751)
('Manchester', 'Old Trafford', 3723)
('Melbourne', 'Melbourne CBD', 3718)
('Birmingham', 'Birmingham Shopping District', 3701)
('Manchester', 'Salford', 3695)
('Berlin', 'Mitte', 3688)
('Sydney', 'Sydney CBD', 3687)
('Sydney', 'Sydney CBD', 3687)
('New Delhi', 'South West Delhi', 3686)
('London', 'Newham', 3682)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 3679)
('London', 'Greenwich', 3675)
('Dubai', 'Downtown Dubai', 3667)
('Dubai', 'Trade Centre', 3666)
('Sydney', 'Sydney CBD', 3666)
('Berlin', 'Friedrichshain-Kreuzberg', 3652)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 3637)
('London', 'Islington', 3627)
('Sydney', 'Sydney CBD', 3627)
('Sydney', 'Sydney CBD', 3615)
('Berlin', 'Prenzlauer Berg', 3600)
('Dubai', 'Beach & Coast', 3591)
('Berlin', 'Mitte', 3576)
('Manchester', 'Manchester City Centre', 3568)
('London', 'Westminster Borough', 3567)
('Dubai', 'Business Bay', 3556)
('Berlin', 'Charlottenburg-Wilmersdorf', 3548)
('Dubai', 'Bur Dubai', 3546)
('Paris', '18th arr.', 3544)
('Berlin', 'Charlottenburg-Wilmersdorf', 3525)
('Melbourne', 'Southbank', 3520)
('Dubai', 'Garhoud', 3516)
('Berlin', 'Neukölln', 3515)
('London', 'Islington', 3510)
('Manchester', 'Manchester City Centre', 3509)
('Birmingham', 'Business District', 3505)
('London', 'Westminster Borough', 3504)
('Berlin', 'Mitte', 3496)
('Melbourne', 'Melbourne CBD', 3485)
('Tokyo', 'Ota Ward', 3471)
('London', 'Greenwich', 3449)
('London', 'Kensington and Chelsea', 3438)
('Dubai', 'Business Bay', 3433)
('Melbourne', 'Southbank', 3430)
('Melbourne', 'Southbank', 3430)
('Dubai', 'Bur Dubai', 3412)
('Dubai', 'Dubai Marina', 3397)
('Sydney', 'Parramatta', 3395)
('Dubai', 'Discovery Gardens', 3391)
('Berlin', 'Mitte', 3384)
('London', 'Greenwich', 3382)
('Kuala Lumpur', 'Bukit Bintang', 3381)
('London', 'Westminster Borough', 3378)
('Toronto', 'North York', 3378)
('New Delhi', 'South West Delhi', 3347)
('Toronto', 'Etobicoke', 3347)
('Berlin', 'Friedrichshain-Kreuzberg', 3343)
('Kuala Lumpur', 'KL Sentral Train Station', 3329)
('Berlin', 'Prenzlauer Berg', 3328)
('London', 'Wandsworth', 3326)
('Berlin', 'Friedrichshain-Kreuzberg', 3322)
('London', 'Westminster Borough', 3321)
('Dubai', 'Al Sufouh', 3317)
('Manchester', 'Old Trafford', 3311)
('Dubai', 'Bur Dubai', 3305)
('Dubai', 'Bur Dubai', 3301)
('Berlin', 'Mitte', 3299)
('Tokyo', 'Koto Ward', 3295)
('Sydney', 'Sydney CBD', 3292)
('Dubai', 'Al Barsha', 3288)
('New Delhi', 'Dwarka', 3286)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 3269)
('Dubai', 'Trade Centre', 3267)
('Berlin', 'Mitte', 3263)
('Sydney', 'Sydney CBD', 3259)
('Dubai', 'Business Bay', 3256)
('Tokyo', 'Ota Ward', 3245)
('London', 'Southwark', 3244)
('Dubai', 'Bur Dubai', 3244)
('Dubai', 'Al Barsha', 3240)
('Paris', '15th arr.', 3231)
('Manchester', 'Manchester City Centre', 3224)
('Dubai', 'Bur Dubai', 3223)
('Tokyo', 'Taito', 3222)
('Tokyo', 'Shinjuku Ward', 3213)
('Manchester', 'Manchester City Centre', 3202)
('Birmingham', 'Eastside', 3195)
('Paris', '18th arr.', 3193)
('Sydney', 'Sydney CBD', 3186)
('Birmingham', 'The Westside', 3184)
('Dubai', 'Garhoud', 3182)
('Paris', 'Paris', 3177)
('Kuala Lumpur', 'Bangsar South', 3176)
('Tokyo', 'Minato', 3169)
('Melbourne', 'Southbank', 3162)
('Birmingham', 'The Westside', 3154)
('Manchester', 'Manchester City Centre', 3141)
('Manchester', 'Manchester City Centre', 3138)
('Paris', '14th arr.', 3097)
('Dubai', 'Al Barsha', 3096)
('Melbourne', 'Melbourne CBD', 3088)
('Melbourne', 'Melbourne CBD', 3087)
('Tokyo', 'Chuo Ward', 3076)
('London', 'Westminster Borough', 3073)
('Dubai', 'Bur Dubai', 3054)
('Manchester', 'Old Trafford', 3044)
('London', 'Westminster Borough', 3027)
('Toronto', 'Financial District', 3022)
('Sydney', 'Sydney CBD', 3017)
('Paris', '18th arr.', 3014)
('Dubai', 'Deira', 2999)
('Paris', '13th arr.', 2990)
('London', 'Westminster Borough', 2988)
('Melbourne', 'Tullamarine', 2982)
('London', 'Southwark', 2979)
('London', 'Westminster Borough', 2963)
('Melbourne', 'Melbourne CBD', 2955)
('London', 'Westminster Borough', 2948)
('Paris', '12th arr.', 2944)
('Melbourne', 'Melbourne CBD', 2923)
('Paris', '14th arr.', 2914)
('Tokyo', 'Taito', 2914)
('Manchester', 'Salford', 2908)
('Sydney', 'Sydney CBD', 2899)
('New Delhi', 'Dwarka', 2895)
('Berlin', 'Treptow-Köpenick', 2894)
('Paris', '17th arr.', 2892)
('London', 'Islington', 2884)
('Berlin', 'Charlottenburg-Wilmersdorf', 2883)
('London', 'Hackney', 2879)
('Melbourne', 'Melbourne CBD', 2874)
('Berlin', 'Mitte', 2871)
('Tokyo', 'Minato', 2866)
('London', 'Kensington and Chelsea', 2865)
('Dubai', 'Al Wasl', 2863)
('Berlin', 'Friedrichshain-Kreuzberg', 2861)
('London', 'Westminster Borough', 2860)
('Berlin', 'Friedrichshain-Kreuzberg', 2859)
('Dubai', 'Beach & Coast', 2857)
('London', 'Hammersmith and Fulham', 2845)
('London', 'Tower Hamlets', 2845)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2845)
('Birmingham', 'Eastside', 2835)
('Birmingham', 'Edgbaston', 2826)
('Kuala Lumpur', 'Pudu', 2818)
('Berlin', 'Spandau', 2798)
('Paris', '15th arr.', 2798)
('Manchester', 'Didsbury', 2797)
('Paris', '9th arr.', 2790)
('London', 'Camden', 2789)
('Dubai', 'Dubai World Central', 2787)
('Sydney', 'Sydney CBD', 2778)
('Sydney', 'Sydney CBD', 2776)
('Sydney', 'Sydney CBD', 2776)
('Birmingham', 'The Westside', 2775)
('Toronto', 'Etobicoke', 2774)
('Melbourne', 'Melbourne CBD', 2770)
('Melbourne', 'Melbourne CBD', 2767)
('Melbourne', 'Melbourne CBD', 2765)
('London', 'Westminster Borough', 2764)
('London', 'Ealing', 2760)
('Birmingham', 'Jewellery Quarter', 2759)
('Berlin', 'Charlottenburg-Wilmersdorf', 2758)
('Paris', '12th arr.', 2757)
('Berlin', 'Friedrichshain-Kreuzberg', 2748)
('New Delhi', 'South West Delhi', 2738)
('Kuala Lumpur', 'Bukit Bintang', 2730)
('London', 'Newham', 2729)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2723)
('London', 'Southwark', 2716)
('Dubai', 'Business Bay', 2715)
('London', 'Camden', 2705)
('Berlin', 'Charlottenburg-Wilmersdorf', 2703)
('Berlin', 'Friedrichshain-Kreuzberg', 2702)
('London', 'Kensington and Chelsea', 2701)
('Paris', '9th arr.', 2699)
('London', 'Greenwich', 2694)
('Manchester', 'Salford', 2692)
('Berlin', 'Charlottenburg-Wilmersdorf', 2690)
('Birmingham', 'Birmingham City Centre', 2685)
('Manchester', 'Manchester City Centre', 2681)
('Tokyo', 'Taito', 2676)
('London', 'Walthamstow', 2672)
('Melbourne', 'Melbourne CBD', 2672)
('Birmingham', 'Birmingham Shopping District', 2669)
('London', 'Newham', 2662)
('Tokyo', 'Koto Ward', 2661)
('Melbourne', 'South Yarra', 2651)
('Berlin', 'Charlottenburg-Wilmersdorf', 2647)
('Dubai', 'Bur Dubai', 2643)
('Sydney', 'Sydney CBD', 2631)
('Dubai', 'Bur Dubai', 2630)
('Tokyo', 'Ota Ward', 2628)
('Kuala Lumpur', 'Brickfields', 2613)
('Paris', '11th arr.', 2609)
('Berlin', 'Mitte', 2607)
('Paris', '17th arr.', 2603)
('Kuala Lumpur', 'KL Sentral Train Station', 2602)
('Dubai', 'Bur Dubai', 2590)
('Tokyo', 'Taito', 2590)
('London', 'Kensington and Chelsea', 2585)
('Paris', '12th arr.', 2571)
('London', 'Newham', 2561)
('New Delhi', 'Paharganj', 2554)
('Paris', '5th arr.', 2551)
('London', 'Westminster Borough', 2550)
('Sydney', 'North Sydney', 2542)
('Sydney', 'Brighton Le Sands', 2539)
('Dubai', 'Beach & Coast', 2533)
('Berlin', 'Mitte', 2530)
('Dubai', 'Deira', 2526)
('Paris', '13th arr.', 2526)
('Tokyo', 'Koto Ward', 2526)
('London', 'Westminster Borough', 2516)
('London', 'Westminster Borough', 2515)
('London', 'Newham', 2512)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2511)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2511)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2508)
('Kuala Lumpur', 'Kuala Lumpur City-Centre', 2508)
('Melbourne', 'Melbourne CBD', 2508)
('Melbourne', 'Melbourne CBD', 2508)
('Melbourne', 'Melbourne CBD', 2505)
('Melbourne', 'Melbourne CBD', 2499)
('Manchester', 'Manchester City Centre', 2492)
('Paris', '5th arr.', 2487)
('Sydney', 'Sydney CBD', 2485)
('Tokyo', 'Toshima', 2483)
('Tokyo', 'Shinjuku Ward', 2479)
('Melbourne', 'Melbourne CBD', 2472)
('Berlin', 'Charlottenburg-Wilmersdorf', 2470)
('Berlin', 'Treptow-Köpenick', 2468)
('Paris', '10th arr.', 2467)

#### 3)  Write a  query that  will retrieve all rows and sort them in descending order of user ratings.

In [18]:
SNo=[]
Hotel=[]
City=[]
Location=[]
reviews=[]
star=[]
userrating=[]

In [19]:
result=cursor.execute("SELECT * FROM DataTable_1 ORDER BY User_rating DESC ")
for _ in result:
    SNo.append(_[0])
    Hotel.append(_[1])
    City.append(_[2])
    Location.append(_[3])
    reviews.append(_[4])
    star.append(_[6])
    userrating.append(_[5])

In [20]:
DF1=pd.DataFrame({'S.no':SNo,'Hotel':Hotel,"City":City,'Location':Location,'Total Reviews':reviews,"Star Rating":star,'User Rating':userrating})
DF1

,S.no,Hotel,City,Location,Total Reviews,Star Rating,User Rating
0,425,Crystal Suites at Axon Residence near Pavilion,Kuala Lumpur,Bukit Bintang,3,5,10.0
1,525,SO Uptown Dubai,Dubai,Deira,72,5,9.8
2,302,Chambers Suites KL BY Fortune,Kuala Lumpur,Chow Kit,26,5,9.6
3,1349,Hôtel des Arts Montmartre,Paris,18th arr.,3014,4,9.6
4,321,Sentral Suites KualaLumpur,Kuala Lumpur,Brickfields,11,5,9.5
...,...,...,...,...,...,...,...
1616,3,Gresham Hotel Bloomsbury,London,Camden,1993,0,4.4
1617,1292,HOTEL ABOUKIR,Paris,2nd arr.,264,0,4.4
1618,1600,West Queen West Hotel,Toronto,The Harbourfront,277,3,4.3
1619,2,City View Hotel - Roman Road Market,London,Tower Hamlets,410,2,4.2
1620,696,The Pleasant House,Manchester,Manchester City Centre,3,0,2.7

####  4)  Write a query that  retrieves rows where the star rating is greater than or equal to 4.0 and sorts them in descending order of review score.

In [21]:
SNo=[]
Hotel=[]
City=[]
Location=[]
reviews=[]
star=[]
userrating=[]

In [22]:
sql="SELECT * FROM DataTable_1 WHERE Star_rating >= 4 ORDER BY User_rating DESC"
result = cursor.execute(sql)
for _ in result:
    SNo.append(_[0])
    Hotel.append(_[1])
    City.append(_[2])
    Location.append(_[3])
    reviews.append(_[4])
    star.append(_[6])
    userrating.append(_[5])

In [23]:
DF2=pd.DataFrame({'S.no':SNo,'Hotel':Hotel,"City":City,'Location':Location,'Total Reviews':reviews,"Star Rating":star,'Review score':userrating})
DF2

,S.no,Hotel,City,Location,Total Reviews,Star Rating,Review score
0,425,Crystal Suites at Axon Residence near Pavilion,Kuala Lumpur,Bukit Bintang,3,5,10.0
1,525,SO Uptown Dubai,Dubai,Deira,72,5,9.8
2,302,Chambers Suites KL BY Fortune,Kuala Lumpur,Chow Kit,26,5,9.6
3,1349,Hôtel des Arts Montmartre,Paris,18th arr.,3014,4,9.6
4,321,Sentral Suites KualaLumpur,Kuala Lumpur,Brickfields,11,5,9.5
...,...,...,...,...,...,...,...
908,278,AEROCITY HOTEL J P PALACE IGI AIRPORT New Delh...,New Delhi,Mahipalpur,72,4,5.8
909,113,Britannia International Hotel Canary Wharf,London,Tower Hamlets,17419,4,5.7
910,257,Hotel Park Tree Near Delhi Airport,New Delhi,South West Delhi,161,4,5.7
911,265,"De Pavilion Hotel, Delhi Airport",New Delhi,Mahipalpur,19,4,5.5
912,598,Raintree Rolla Hotel,Dubai,Bur Dubai,3054,4,4.6

#### 5)  Write a query to count the number of hotels in each city.

In [24]:
sql="SELECT City, COUNT(*) AS HotelCount FROM DataTable_1 GROUP BY City"
result = cursor.execute(sql)
rows = result.fetchall()

for row in rows:
    city = row[0]
    hotel_count = row[1]
    print(f"City: {city}, Hotel Count: {hotel_count}")

City: Berlin, Hotel Count: 150
City: Birmingham, Hotel Count: 74
City: Dubai, Hotel Count: 151
City: Kuala Lumpur, Hotel Count: 150
City: London, Hotel Count: 151
City: Manchester, Hotel Count: 99
City: Melbourne, Hotel Count: 150
City: New Delhi, Hotel Count: 150
City: Paris, Hotel Count: 151
City: Sydney, Hotel Count: 150
City: Tokyo, Hotel Count: 150
City: Toronto, Hotel Count: 95

# Table 2

#### 1) Write a query to retrieve hotels that have both a restaurant and a bar

In [25]:
# Defining SQL query
sql = "SELECT Hotel, Restaurant, Bar FROM DataTable_2 WHERE Restaurant = 'yes' AND Bar = 'yes'"

# Execute the SQL query
cursor.execute(sql)

# Initialize lists to store results
Hotel = []
Restaurant = []
Bar = []

# Fetch and append results to the lists
for row in cursor.fetchall():
    Hotel.append(row[0])
    Restaurant.append(row[1])
    Bar.append(row[2])

In [26]:
print(len(Hotel)),print(len(Restaurant)),print(len(Bar))

909
909
909

(None, None, None)

In [27]:
DF=pd.DataFrame({'Hotel':Hotel,"Restaurant":Restaurant,'Bar':Bar})
DF

                                                 Hotel Restaurant  Bar
0                 Earls Court East Serviced Apartments        yes  yes
1                                   The Langham London        yes  yes
2                  City View Hotel - Roman Road Market        yes  yes
3                             Gresham Hotel Bloomsbury        yes  yes
4                  Maldron Hotel Finsbury Park, London        yes  yes
..                                                 ...        ...  ...
904                      Pantages Hotel Toronto Centre        yes  yes
905                              The St. Regis Toronto        yes  yes
906                          The Ritz-Carlton, Toronto        yes  yes
907                  Yonge Suites Furnished Apartments        yes  yes
908  Residence Inn by Marriott Toronto Downtown / E...        yes  yes

[909 rows x 3 columns]

#### 2) Write a query to retrieve hotels that offer free WiFi and have family rooms.

In [28]:
# Defining SQL query
sql = "SELECT Hotel,Free_wifi,Family_rooms FROM DataTable_2 WHERE Free_wifi = 'yes' AND Family_rooms = 'yes'"

# Execute the SQL query
cursor.execute(sql)

# Initialize lists to store results
Hotel = []
freewifi = []
familyroom = []

# Fetch and append results to the lists
for row in cursor.fetchall():
    Hotel.append(row[0])
    freewifi.append(row[1])
    familyroom.append(row[2])

In [29]:
DF=pd.DataFrame({'Hotel':Hotel,"Free Wifi":freewifi,'Family Rooms':familyroom})
DF

                                                  Hotel Free Wifi Family Rooms
0                  Earls Court East Serviced Apartments       yes          yes
1                                    The Langham London       yes          yes
2                   Maldron Hotel Finsbury Park, London       yes          yes
3     Radisson Blu Edwardian New Providence Wharf Ho...       yes          yes
4     Holiday Inn Express London Chingford, an IHG H...       yes          yes
...                                                 ...       ...          ...
1257                      Pantages Hotel Toronto Centre       yes          yes
1258                              The St. Regis Toronto       yes          yes
1259                          Kensington Place Property       yes          yes
1260                  Yonge Suites Furnished Apartments       yes          yes
1261  Residence Inn by Marriott Toronto Downtown / E...       yes          yes

[1262 rows x 3 columns]

#### 3) Write a query to count the occurrences of each breakfast cuisine type.

In [30]:
sql_queries = [
    "SELECT 'Breakfast_Cuisine1_Continental' AS Cuisine_Type, COUNT(*) FROM DataTable_2 WHERE Breakfast_Cuisine1_Continental = 'yes'",
    "SELECT 'Breakfast_Cuisine2_Vegetarian' AS Cuisine_Type, COUNT(*) FROM DataTable_2 WHERE Breakfast_Cuisine2_Vegetarian = 'yes'",
    "SELECT 'Breakfast_Cuisine3_American' AS Cuisine_Type, COUNT(*) FROM DataTable_2 WHERE Breakfast_Cuisine3_American = 'yes'"
]

# Initialize an empty dictionary to store the results
results = {}

# Execute the SQL queries and store the results in the dictionary
for query in sql_queries:
    cursor.execute(query)
    row = cursor.fetchone()
    cuisine_type = row[0]
    count = row[1]
    results[cuisine_type] = count

# Print the results
for cuisine_type, count in results.items():
    print(f"{cuisine_type}: {count}")

Breakfast_Cuisine1_Continental: 776
Breakfast_Cuisine2_Vegetarian: 508
Breakfast_Cuisine3_American: 350

#### 4) Write a query to retrieve hotels that offer a certain(CONTINENTAL )  breakfast cuisine .{{Students you may give any cuisine as per your choices}}

In [31]:
sql="SELECT Hotel,Breakfast_Cuisine1_Continental From DataTable_2 WHERE Breakfast_Cuisine1_Continental='yes'"
result=cursor.execute(sql)
hotel=[]
continental=[]

for row in result:
    hotel.append(row[0])
    continental.append(row[1])

In [32]:
DF=pd.DataFrame({'Hotel':hotel,"Continental food":continental})
DF

                                                 Hotel Continental food
0                                   The Langham London              yes
1                  Maldron Hotel Finsbury Park, London              yes
2    Holiday Inn Express London Chingford, an IHG H...              yes
3                                ibis London Stratford              yes
4                               Royal Lancaster London              yes
..                                                 ...              ...
771                         The Omni King Edward Hotel              yes
772                                          EST Hotel              yes
773                          The Ritz-Carlton, Toronto              yes
774          Residence Inn by Marriott Toronto Airport              yes
775  Residence Inn by Marriott Toronto Downtown / E...              yes

[776 rows x 2 columns]

#### 5) Write a query to see whether an hotel has all amenities such as Heating, Lift and Bar.

In [33]:
sql="SELECT HOTEL,Bar,Heating,Lift FROM DataTable_2"
result=cursor.execute(sql)
hotel=[]
Bar=[]
Heating=[]
Lift=[]
for i in result:
    hotel.append(i[0])
    Bar.append(i[1])
    Heating.append(i[2])
    Lift.append(i[3])

In [34]:
DF=pd.DataFrame({'Hotel':hotel,"Bar":Bar,"Heating":Heating,"Lift":Lift})
DF

                                                  Hotel  Bar Heating Lift
0                  Earls Court East Serviced Apartments  yes     yes  yes
1                                    The Langham London  yes     yes  yes
2                   City View Hotel - Roman Road Market  yes     yes  yes
3                              Gresham Hotel Bloomsbury  yes     yes  yes
4                   Maldron Hotel Finsbury Park, London  yes     yes  yes
...                                                 ...  ...     ...  ...
1616                          Kensington Place Property   No      No   No
1617                                   Casa Queen Hotel   No     yes   No
1618                  Yonge Suites Furnished Apartments  yes     yes  yes
1619          Residence Inn by Marriott Toronto Airport   No     yes  yes
1620  Residence Inn by Marriott Toronto Downtown / E...  yes     yes  yes

[1621 rows x 4 columns]

# Table 3

#### 1) Write SQL query to retrieve hotels that offer double bed rooms and sort them by price in descending order

In [35]:
sql="SELECT Hotel,Double_bed,Price_in_INR FROM DataTable_3 WHERE Double_bed='yes' ORDER BY Price_in_INR DESC"
result=cursor.execute(sql)
hotel=[]
doublebed=[]
price=[]
for u in result:
    hotel.append(u[0])
    doublebed.append(u[1])
    price.append(u[2])

In [36]:
DF=pd.DataFrame({"Hotel":hotel,"Double Bed Availability":doublebed,"Price":price})
DF

,Hotel,Double Bed Availability,Price
0,The Peninsula Tokyo,yes,123974
1,"Shangri-La The Shard, London",yes,86460
2,SO Paris Hotel,yes,74377
3,The Ultimate Hen Suite,yes,66645
4,The Ultimate Hen Suite with Bar & Makeup Room,yes,66645
...,...,...,...
1436,The Ramida Suites At Delhi Airport,yes,1029
1437,"Hotel Shivdev International, Near New Delhi Ra...",yes,1025
1438,Sun Inns Hotel Batu Caves,yes,982
1439,Hotel Marina A Family Hotel Near IGI Airport B...,yes,968
1440,"Hotel Delish Hospitality Near Laxmi Nagar "" Co...",yes,872

#### 2) Write a SQL query to calculate the average price for each room type.

In [37]:
sql="SELECT Room_Type, AVG(Price_in_INR) AS Average_Price FROM DataTable_3 GROUP BY Room_Type"
result=cursor.execute(sql)
for i in result:
    print(i)

('Deluxe Room', 12083.968325791855)
('Deluxe Room ', 14903.666666666666)
('Double Room', 12095.238578680202)
('Double Room ', 9506.0)
('Economy Room', 8440.877551020409)
('King Room', 13492.321167883212)
('Queen Room', 11955.986363636364)
('Standard Room', 11191.389312977099)

#### 3) Write a query to find details of hotels with user ratings, above 5 as a  threshold and that offer free WiFi.(Use table1 and table2)

In [38]:
sql="SELECT Hotel,City,location,Star_rating,User_rating FROM DataTable_1 WHERE User_rating > 5 AND Hotel IN (SELECT Hotel FROM DataTable_2 WHERE Free_Wifi='yes')"
result=cursor.execute(sql)
for i in result:
    print(i)

('Earls Court East Serviced Apartments', 'London', 'Kensington and Chelsea', 4, 8.1)
('The Langham London', 'London', 'Westminster Borough', 5, 9.2)
('Maldron Hotel Finsbury Park, London', 'London', 'Islington', 4, 8.5)
('The May Fair, A Radisson Collection Hotel, Mayfair London', 'London', 'Westminster Borough', 5, 8.1)
('Radisson Blu Edwardian New Providence Wharf Hotel, London', 'London', 'Tower Hamlets', 4, 8.8)
('Holiday Inn Express London Chingford, an IHG Hotel', 'London', 'Walthamstow', 3, 7.1)
('ibis London Stratford', 'London', 'Newham', 3, 7.8)
('Zedwell Underground Tottenham Court Rd', 'London', 'Camden', 3, 6.4)
('Leonardo Royal London St Paul’s', 'London', 'City of London', 4, 8.5)
('Royal Lancaster London', 'London', 'Westminster Borough', 5, 9.0)
('The Tower Hotel', 'London', 'Tower Hamlets', 4, 7.8)
('Alexandra Hotel', 'London', 'Westminster Borough', 3, 7.1)
('Hotel Saint London', 'London', 'Hackney', 4, 8.4)
('citizenM London Shoreditch', 'London', 'Hackney', 4, 8.7)
('Keystone House', 'London', 'Islington', 3, 7.9)
('The Beaufort', 'London', 'Kensington and Chelsea', 4, 7.3)
('Argo Hotel - Kings Cross', 'London', 'Camden', 3, 7.9)
('Langham Court Hotel', 'London', 'Westminster Borough', 4, 7.1)
('Homefield Lodge', 'London', 'Brent', 2, 8.1)
('The Piccadilly London West End', 'London', 'Westminster Borough', 5, 8.0)
('DoubleTree by Hilton Hotel London - Tower of London', 'London', 'Islington', 4, 7.6)
('Montcalm Royal London House-City of London', 'London', 'Islington', 5, 8.3)
('Park Avenue Bayswater Inn Hyde Park', 'London', 'Westminster Borough', 4, 7.4)
('Seraphine Hammersmith Hotel', 'London', 'Hammersmith and Fulham', 4, 7.8)
('Best Western Mornington Hotel Hyde Park', 'London', 'Westminster Borough', 4, 7.3)
('Park Grand London Kensington', 'London', 'Kensington and Chelsea', 4, 8.0)
('Moxy London Stratford', 'London', 'Newham', 4, 8.2)
('Hilton London Olympia', 'London', 'Kensington and Chelsea', 4, 7.0)
('DoubleTree by Hilton London – West End', 'London', 'Camden', 4, 7.1)
('citizenM Tower of London', 'London', 'Camden', 4, 8.6)
('Argyle Square Hotel', 'London', 'Camden', 0, 6.9)
('Hilton London Bankside', 'London', 'Southwark', 5, 8.9)
('London Lodge Hotel', 'London', 'Kensington and Chelsea', 3, 8.1)
('Holiday Inn London Kensington High St., an IHG Hotel', 'London', 'Kensington and Chelsea', 4, 7.1)
('The Brent Hotel - London - Wembley and Harrow', 'London', 'Brent', 3, 7.9)
('DoubleTree by Hilton London – Docklands Riverside', 'London', 'Southwark', 4, 7.9)
('Holiday Inn Express Southwark, an IHG Hotel', 'London', 'Southwark', 3, 8.2)
('Ember Locke', 'London', 'Kensington and Chelsea', 4, 8.9)
('The Westminster London, Curio Collection by Hilton', 'London', 'Westminster Borough', 4, 8.3)
('Hilton London Euston', 'London', 'Camden', 4, 7.1)
('Radisson Blu Edwardian Hampshire Hotel, London', 'London', 'Westminster Borough', 5, 8.4)
('The Westbridge Hotel Stratford', 'London', 'Newham', 4, 8.2)
('Hyatt Regency London Stratford', 'London', 'Newham', 4, 8.3)
('Mornington Hotel London Victoria', 'London', 'Westminster Borough', 4, 7.6)
('Courtyard by Marriott London City Airport', 'London', 'Newham', 4, 8.6)
('Royal Park Hotel', 'London', 'Westminster Borough', 3, 7.0)
('Royal Hotel', 'London', 'Westminster Borough', 4, 7.0)
('Ivy House Hotel', 'London', 'Westminster Borough', 3, 6.4)
('Radisson Blu Edwardian Vanderbilt Hotel, London', 'London', 'Kensington and Chelsea', 4, 7.7)
('NOX Edgware Road', 'London', 'Westminster Borough', 4, 8.0)
('The Dilly', 'London', 'Westminster Borough', 5, 8.0)
('Sidney Hotel London-Victoria', 'London', 'Westminster Borough', 3, 7.8)
('President Hotel', 'London', 'Camden', 3, 7.3)
('One Hundred Shoreditch', 'London', 'Hackney', 5, 8.7)
('The Barbican Rooms', 'London', 'Islington', 5, 7.5)
('Messina Studios', 'London', 'Camden', 3, 7.5)
('The Mandeville Hotel', 'London', 'Westminster Borough', 4, 8.1)
('The Nayland Hotel', 'London', 'Westminster Borough', 3, 7.0)
('Novotel London Greenwich', 'London', 'Greenwich', 4, 7.5)
('Holiday Inn Express London - Wandsworth, an IHG Hotel', 'London', 'Wandsworth', 3, 7.7)
('100 Queen’s Gate Hotel London, Curio Collection by Hilton', 'London', 'Kensington and Chelsea', 5, 7.8)
('DoubleTree by Hilton London Victoria', 'London', 'Westminster Borough', 4, 7.7)
('Leonardo Royal Hotel London City - Tower of London', 'London', 'Greenwich', 4, 8.3)
('Hotel 55', 'London', 'Ealing', 4, 8.0)
('St Mark Hotel', 'London', 'Kensington and Chelsea', 3, 5.4)
('Hilton London Paddington', 'London', 'Westminster Borough', 4, 7.3)
('Doubletree By Hilton London - Greenwich', 'London', 'Greenwich', 4, 8.2)
('DoubleTree By Hilton London Excel', 'London', 'Newham', 4, 7.9)
('Leonardo Royal London Tower Bridge', 'London', 'Tower Hamlets', 4, 8.0)
('DoubleTree by Hilton London - Hyde Park', 'London', 'Kensington and Chelsea', 4, 7.6)
('ME London by Melia', 'London', 'Westminster Borough', 5, 8.5)
('The Hoxton, Shepherds Bush', 'London', 'Hammersmith and Fulham', 4, 8.7)
('ibis London City - Shoreditch', 'London', 'Tower Hamlets', 3, 7.9)
('Sun Street Hotel Shoreditch', 'London', 'Hackney', 5, 8.9)
('Gunmakers', 'London', 'Westminster Borough', 0, 8.5)
('Radisson Blu Edwardian Bloomsbury Street Hotel, London', 'London', 'Camden', 4, 8.4)
('The Londoner', 'London', 'Westminster Borough', 5, 9.1)
('Doubletree By Hilton London Kensington', 'London', 'Kensington and Chelsea', 4, 7.3)
('The Cumberland', 'London', 'Westminster Borough', 4, 8.1)
('Clayton Hotel London Wall', 'London', 'Lambeth', 4, 8.9)
('Dorsett Shepherds Bush London', 'London', 'Hammersmith and Fulham', 4, 7.8)
('Grand Royale London Hyde Park', 'London', 'Westminster Borough', 4, 6.9)
('Park Plaza London Riverbank', 'London', 'Lambeth', 4, 8.1)
('Grange Clarendon Hotel', 'London', 'Camden', 4, 7.0)
('The Z Hotel Trafalgar', 'London', 'Westminster Borough', 0, 8.4)
('Holiday Inn Express London-Hammersmith, an IHG Hotel', 'London', 'Hammersmith and Fulham', 3, 8.0)
('Holiday Inn Express London - ExCel, an IHG Hotel', 'London', 'Newham', 3, 8.1)
('Nobu Hotel London Portman Square', 'London', 'Westminster Borough', 5, 8.6)
('Crowne Plaza London Kings Cross, an IHG Hotel', 'London', 'Islington', 4, 7.6)
('Room Home Stay', 'London', 'Greenwich', 4, 7.6)
('The Montcalm At Brewery London City', 'London', 'Greenwich', 5, 6.9)
('Bedford Corner Hotel', 'London', 'Camden', 4, 7.7)
('The Gantry London, Curio Collection By Hilton', 'London', 'Newham', 4, 8.7)
('Heeton Concept Hotel – Luma Hammersmith', 'London', 'Hammersmith and Fulham', 4, 7.8)
('DoubleTree by Hilton London Ealing', 'London', 'Ealing', 4, 7.7)
('NOX Waterloo', 'London', 'Lambeth', 4, 8.2)
('Merit Kensington Hotel', 'London', 'Kensington and Chelsea', 4, 8.1)
('Glendale Hyde Park Hotel', 'London', 'Westminster Borough', 3, 6.3)
('Hart Shoreditch Hotel London, Curio Collection by Hilton', 'London', 'Hackney', 4, 9.0)
('Holiday Inn Express Royal Docks, an IHG Hotel', 'London', 'Newham', 3, 7.7)
('Hilton London Kensington Hotel', 'London', 'Kensington and Chelsea', 4, 6.9)
('Radisson Blu Edwardian Grafton Hotel, London', 'London', 'Camden', 4, 8.0)
('Zedwell Piccadilly Circus', 'London', 'Westminster Borough', 0, 7.5)
('Signature Townhouse London Hyde Park', 'London', 'Westminster Borough', 4, 7.0)
('Novotel London Tower Bridge', 'London', 'Greenwich', 4, 8.6)
('1 Hotel Mayfair', 'London', 'Westminster Borough', 5, 9.0)
('Britannia International Hotel Canary Wharf', 'London', 'Tower Hamlets', 4, 5.7)
('The Stratford Hotel London', 'London', 'Newham', 5, 8.6)
('The Chamberlain', 'London', 'Greenwich', 4, 8.5)
('Flexistay Norbury Aparthotel', 'London', 'Greenwich', 3, 6.9)
('Manor Hotel', 'London', 'Kensington and Chelsea', 2, 6.6)
('Shangri-La The Shard, London', 'London', 'Southwark', 5, 9.0)
('New Road Hotel', 'London', 'Tower Hamlets', 4, 8.0)
('Chelsea House Hotel - B&B', 'London', 'Kensington and Chelsea', 2, 7.6)
('Hampton by Hilton London Waterloo', 'London', 'Lambeth', 3, 8.2)
('NOX Hyde Park', 'London', 'Westminster Borough', 4, 7.0)
('Park Plaza Westminster Bridge London', 'London', 'Lambeth', 4, 8.3)
('Commodore Hotel', 'London', 'Westminster Borough', 3, 7.6)
('Green Rooms', 'London', 'Islington', 0, 7.2)
('Pestana Chelsea Bridge Hotel', 'London', 'Wandsworth', 4, 8.2)
('Apex Temple Court Hotel', 'London', 'Greenwich', 4, 8.9)
('Best Western Corona Hotel', 'London', 'Westminster Borough', 3, 7.2)
('Fountain Hotel', 'London', 'Lambeth', 2, 7.2)
('Hilton London Hyde Park', 'London', 'Bayswater', 4, 7.4)
('The Standard London', 'London', 'Camden', 5, 8.6)
('Grange Buckingham Hotel', 'London', 'Camden', 4, 7.6)
('citizenM London Victoria Station', 'London', 'Westminster Borough', 4, 8.9)
('TRIBE London Canary Wharf', 'London', 'Tower Hamlets', 4, 8.4)
('The Sanctuary House Hotel', 'London', 'Westminster Borough', 3, 8.6)
('Apex City Of London Hotel', 'London', 'Westminster Borough', 4, 8.8)
('Citadines Barbican London', 'London', 'Islington', 4, 8.2)
('NOX Belsize Park', 'London', 'Camden', 3, 7.2)
('ibis London Shepherds Bush - Hammersmith', 'London', 'Hammersmith and Fulham', 3, 7.9)
('Sea Containers London', 'London', 'Southwark', 5, 8.8)
('Park Avenue J Hotel London Hyde Park', 'London', 'Westminster Borough', 4, 7.2)
('Hyatt House London Stratford - Aparthotel', 'London', 'Newham', 4, 8.7)
('citizenM London Bankside', 'London', 'Southwark', 4, 8.6)
('DoubleTree by Hilton Hotel London - Marble Arch', 'London', 'Westminster Borough', 4, 7.3)
('The City of London Club', 'London', 'Southwark', 0, 9.2)
('Sloane Square Hotel', 'London', 'Kensington and Chelsea', 4, 7.8)
('CG Kensington', 'London', 'Kensington and Chelsea', 4, 8.2)
('146 Studios', 'London', 'Westminster Borough', 4, 7.5)
('Clayton Hotel City of London', 'London', 'Tower Hamlets', 4, 8.6)
('Copthorne Tara Hotel London Kensington', 'London', 'Kensington and Chelsea', 4, 6.9)
('Hotel Delish Hospitality Near Laxmi Nagar " Couple Friendly "', 'New Delhi', 'East Delhi', 3, 7.7)
('Palm Everland', 'New Delhi', 'South West Delhi', 3, 8.0)
('Skon Boutique by Orion Hotels', 'New Delhi', 'South Delhi', 3, 7.7)
('Hotel Tripple Tree - Karol Bagh', 'New Delhi', 'Karol bagh', 4, 8.1)
('THE SINGH EMPIRE, New Delhi', 'New Delhi', 'Paharganj', 4, 7.9)
('Hotel Grand Suites Delhi Airport By D Capitol', 'New Delhi', 'South West Delhi', 4, 7.8)
('The Leela Ambience Convention Hotel Delhi', 'New Delhi', 'East Delhi', 5, 8.5)
('Hotel Shivdev International, Near New Delhi Railway Station', 'New Delhi', 'Paharganj', 3, 7.2)
('The Ramida Suites At Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 7.9)
('Hotel City Empire', 'New Delhi', 'Paharganj', 3, 8.1)
('Staybook - Hotel City Stories - By Aira Xing, Paharganj, New Delhi', 'New Delhi', 'Paharganj', 4, 7.8)
('Holiday Inn New Delhi International Airport, an IHG Hotel', 'New Delhi', 'South West Delhi', 5, 7.8)
('Hotel Caves A Family Hotel Near IGI Airport Delhi', 'New Delhi', 'South West Delhi', 4, 7.4)
('The Raj New Delhi', 'New Delhi', 'Paharganj', 4, 8.9)
('Crowne Plaza New Delhi Mayur Vihar Noida, an IHG Hotel', 'New Delhi', 'Mayur Vihar Phase 1', 5, 8.2)
('Hotel Ark Suites At Delhi Airport', 'New Delhi', 'South West Delhi', 3, 7.9)
('Hotel Blue Pearl', 'New Delhi', 'Paharganj', 3, 8.2)
('Yes Boss By Backpackers Heaven Near New Delhi Train Station', 'New Delhi', 'Paharganj', 3, 7.8)
('Airport Hotel Grand, New Delhi', 'New Delhi', 'Mahipalpur', 4, 7.9)
('Hotel Marina A Family Hotel Near IGI Airport BY AR', 'New Delhi', 'South West Delhi', 4, 7.2)
('Hotel Neu Villa - Walk In from New Delhi Railway Station', 'New Delhi', 'Paharganj', 4, 7.5)
('Hotel Ajanta', 'New Delhi', 'Paharganj', 3, 7.2)
('Hotel Decent Suites - Delhi Airport', 'New Delhi', 'South West Delhi', 4, 7.7)
('Aloft New Delhi Aerocity', 'New Delhi', 'South West Delhi', 5, 8.2)
('Airport Hotel IVY', 'New Delhi', 'South West Delhi', 3, 7.5)
('Hotel SAMRAT RESIDENCY', 'New Delhi', 'South West Delhi', 4, 8.5)
('Hotel TEJ Palace By Tark A Family Hotel', 'New Delhi', 'South West Delhi', 4, 7.0)
('Hotel Shri Vinayak at New Delhi Railway Station-By RCG Hotels', 'New Delhi', 'Paharganj', 3, 8.2)
('HOTEL AMBIENCE DX PAHARGANJ NEW Delhi NEAR Rk ASHRAM METRO STATION', 'New Delhi', 'Paharganj', 3, 8.5)
('Frank Stay By Hotel Preet in 05 mints walking Distance Nizamuddin Railway Station', 'New Delhi', 'South Delhi', 4, 8.5)
("Hotel D'Capitol Suites Delhi Aerocity", 'New Delhi', 'South West Delhi', 4, 7.7)
('Cosy Grand, Near Chanakyapuri, Embassy Area', 'New Delhi', 'South Delhi', 3, 8.1)
('Novotel New Delhi Aerocity- International Airport', 'New Delhi', 'South West Delhi', 5, 7.7)
('Hotel Preet Palace -5 Mints Walk From Nizamuddin Railway Station', 'New Delhi', 'South Delhi', 4, 7.5)
('Hotel Le-Mount Near IGI Airport Delhi', 'New Delhi', 'South West Delhi', 4, 7.5)
('Hotel Town Pallace Inn Patel Nagar New Delhi', 'New Delhi', 'East Delhi', 3, 7.5)
('Park Inn by Radisson,South Delhi', 'New Delhi', 'South Delhi', 5, 7.7)
('Hotel Aero Star Near Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 8.0)
('Hotel King Plaza', 'New Delhi', 'South West Delhi', 4, 6.5)
('Hotel Anand - By Srida Hotels', 'New Delhi', 'Paharganj', 4, 7.0)
('Hotel Clayton Near IGI Airport Delhi', 'New Delhi', 'South West Delhi', 4, 6.3)
('Four Points by Sheraton New Delhi, Airport Highway', 'New Delhi', 'South West Delhi', 4, 7.9)
('Jyoti Mahal A Heritage Hotel - 05 Mins from New Delhi Railway Station', 'New Delhi', 'Paharganj', 4, 7.5)
('Hotel Amar International', 'New Delhi', 'Paharganj', 3, 7.2)
('Ambassador, New Delhi - IHCL SeleQtions', 'New Delhi', 'Central Delhi', 5, 7.8)
('Hotel Harsha International', 'New Delhi', 'Paharganj', 3, 7.0)
('Hotel Ananda', 'New Delhi', 'Karol bagh', 3, 8.4)
('Hotel Smart Plaza Delhi Airport', 'New Delhi', 'South West Delhi', 4, 7.4)
('Hotel The Pearl', 'New Delhi', 'Paharganj', 3, 7.5)
("Singh's Hotel", 'New Delhi', 'Karol bagh', 0, 6.4)
('Private Luxury Hygienic Rooms In Lajpat Nagar', 'New Delhi', 'South Delhi', 3, 7.5)
('Hotel Pearl - Mahipalpur Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 8.4)
('FabHotel Skye Suites', 'New Delhi', 'Mahipalpur', 4, 8.7)
('The Ashok, New Delhi', 'New Delhi', 'Chanakyapuri', 5, 6.7)
('Hotel Classic - Near Nizamuddin Railway Station', 'New Delhi', 'South Delhi', 3, 7.3)
('Holiday Inn New Delhi Mayur Vihar Noida, an IHG Hotel', 'New Delhi', 'Mayur Vihar Phase 1', 5, 7.5)
('Hotel Red Velvet At Delhi Airport', 'New Delhi', 'South West Delhi', 3, 7.6)
('Radisson Blu Plaza Delhi Airport', 'New Delhi', 'Mahipalpur', 5, 8.1)
('HOTEL SINGH CONTINETAL', 'New Delhi', 'Karol bagh', 3, 8.4)
('ibis New Delhi Aerocity - An Accor Brand', 'New Delhi', 'South West Delhi', 4, 6.8)
('Crowne Plaza New Delhi Okhla, an IHG Hotel', 'New Delhi', 'South Delhi', 5, 7.9)
('Airport Hotel Ramhan Palace Mahipalpur', 'New Delhi', 'Mahipalpur', 4, 7.9)
("Hotel Nitya Maharani ' Near New Delhi Railway Station '", 'New Delhi', 'Paharganj', 3, 8.0)
('OYO Flagship 72474 BEST HOMESTAY Near Nizanuddin', 'New Delhi', 'South Delhi', 3, 7.8)
('Zone Connect by The Park Saket New Delhi', 'New Delhi', 'Saket', 5, 7.3)
('Hotel IVY plaza Luxury', 'New Delhi', 'South West Delhi', 3, 7.4)
('The Gold Regency - 02 Mins from New Delhi Railway Station', 'New Delhi', 'Paharganj', 3, 7.2)
('HOTEL DELHI 55 @ NEW DELHI RAILWAY STATION', 'New Delhi', 'Paharganj', 3, 7.7)
('Hotel Ambience Suites Delhi Airport', 'New Delhi', 'Mahipalpur', 4, 7.6)
('Hotel Bluestone - Nehru Place', 'New Delhi', 'South Delhi', 4, 7.8)
('Hotel Festival Mahipalpur At Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 9.1)
('Welcomhotel by ITC Hotels, Dwarka, New Delhi', 'New Delhi', 'Dwarka', 5, 7.0)
('FabHotel Chattarpur Enclave', 'New Delhi', 'Chattarpur', 3, 7.1)
('Jupiter Plaza Delhi Airport', 'New Delhi', 'South West Delhi', 3, 7.2)
('Hotel Krishna - By RCG Hotels', 'New Delhi', 'Paharganj', 3, 8.0)
('Hotel Star Villa - Budget Friendly', 'New Delhi', 'Paharganj', 3, 6.8)
('FabHotel Exotica Greenpark', 'New Delhi', 'South Delhi', 3, 7.7)
('Trimrooms Shipra @ New Delhi Railway Station', 'New Delhi', 'Paharganj', 3, 7.3)
('Majestic Stay - East of Kailash', 'New Delhi', 'South Delhi', 4, 9.2)
('The Alpino Hotel', 'New Delhi', 'Mahipalpur', 4, 7.0)
('Hotel Trans International - Near Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 7.1)
('Hotel Star One - Near Delhi Airport', 'New Delhi', 'Mahipalpur', 3, 8.0)
('Le Meridien New Delhi', 'New Delhi', 'Central Delhi', 5, 7.8)
('Hotel Bricks, Karol Bagh, New Delhi', 'New Delhi', 'Karol bagh', 3, 8.1)
('Airport Hotel Clayton', 'New Delhi', 'South West Delhi', 3, 7.6)
('Vivanta New Delhi, Dwarka', 'New Delhi', 'Dwarka', 5, 8.1)
('Hotel Rosewood Near Delhi Airport', 'New Delhi', 'South West Delhi', 4, 7.0)
('Hotel Lotus Stay At Delhi Airport', 'New Delhi', 'South West Delhi', 3, 7.6)
('The Prime Balaji Deluxe @ New Delhi Railway Station', 'New Delhi', 'Paharganj', 3, 7.9)
('Radisson Blu Marina Hotel Connaught Place', 'New Delhi', 'Connaught Place', 5, 7.2)
('Grand Godwin Near NDLS Railway Station- Paharganj', 'New Delhi', 'Paharganj', 3, 7.5)
('Hotel City lite Near IGI Airport', 'New Delhi', 'South West Delhi', 4, 7.0)
('The Ashtan Sarovar Portico', 'New Delhi', 'South Delhi', 4, 7.7)
('HOTEL GEESON -New Delhi Railway Station -Paharganj', 'New Delhi', 'Paharganj', 3, 7.8)
('Hotel Tom - Jungpura Chruch Road', 'New Delhi', 'South Delhi', 3, 8.1)
('Hotel Sai Miracle - 5 mint from New Delhi railway station', 'New Delhi', 'Paharganj', 3, 7.4)
('Hotel Asian Blue IGi Airport Delhi', 'New Delhi', 'South West Delhi', 3, 7.2)
('Hotel Park Tree Near Delhi Airport', 'New Delhi', 'South West Delhi', 4, 5.7)
('The Saina International- New Delhi, Paharganj', 'New Delhi', 'Paharganj', 4, 8.9)
('The Orion - Greater Kailash', 'New Delhi', 'Greater Kailash 1', 4, 7.3)
('Roomshala 002 Hotel Rose Residency - Near Sector 9 Metro Station', 'New Delhi', 'Dwarka', 3, 6.6)
('Pride Plaza Hotel, Aerocity New Delhi', 'New Delhi', 'South West Delhi', 5, 7.5)
('Hotel S B INN Paharganj', 'New Delhi', 'Paharganj', 0, 9.1)
('The Oakland Plaza by Orion Hotels', 'New Delhi', 'South Delhi', 3, 7.1)
('The Leela Palace New Delhi', 'New Delhi', 'South Delhi', 5, 9.0)
('De Pavilion Hotel, Delhi Airport', 'New Delhi', 'Mahipalpur', 4, 5.5)
('The Leena International -New Delhi', 'New Delhi', 'Paharganj', 4, 7.9)
('MGM Residency', 'New Delhi', 'Dariyaganj', 3, 8.5)
('Hotel Mannat international by Mannat', 'New Delhi', 'Paharganj', 3, 8.1)
('Hotel The Kiara Delhi Airport', 'New Delhi', 'South West Delhi', 3, 6.8)
('Hotel Batra Home 5 Mint Walk From Nizamuddin Railway Station', 'New Delhi', 'South Delhi', 3, 7.1)
('Airport Ostella Grand', 'New Delhi', 'South West Delhi', 0, 7.5)
('Pullman New Delhi Aerocity- International Airport', 'New Delhi', 'South West Delhi', 5, 8.2)
('Delhi Pride Hotel', 'New Delhi', 'Karol bagh', 3, 6.8)
("Hotel Palm D'or", 'New Delhi', 'Paharganj', 3, 8.0)
('Radisson Blu Hotel New Delhi Dwarka', 'New Delhi', 'Dwarka', 5, 6.5)
('Hotel The Best Near Delhi Airport', 'New Delhi', 'South West Delhi', 4, 6.7)
('AEROCITY HOTEL J P PALACE IGI AIRPORT New Delhi BY SHOAIB TRAVELS', 'New Delhi', 'Mahipalpur', 4, 5.8)
('The Claridges New Delhi', 'New Delhi', 'Central Delhi', 5, 7.8)
('Hotel Ritz', 'New Delhi', 'Paharganj', 3, 7.9)
('Gallivanto Inn', 'New Delhi', 'Rohini', 3, 8.4)
('Hotel Shelton', 'New Delhi', 'Paharganj', 3, 7.4)
('Hotel Uppal International - New Delhi Railway Station - Paharganj', 'New Delhi', 'Paharganj', 3, 6.9)
('Hyatt Centric Janakpuri New Delhi', 'New Delhi', 'Janakpuri', 5, 6.5)
('The Lodhi – A member of The Leading Hotels Of The World', 'New Delhi', 'Rohini', 5, 8.5)
('Airport Hotel Tashree', 'New Delhi', 'South West Delhi', 3, 7.5)
('Hotel Saffron Gold', 'New Delhi', 'Pashim Vihar', 3, 7.3)
('Itsy By Treebo - Connaught Mews', 'New Delhi', 'Connaught Place', 3, 6.5)
('Grand Tashree', 'New Delhi', 'South West Delhi', 4, 6.9)
('Hotel Arch Plaza - Near Delhi Airport', 'New Delhi', 'South West Delhi', 4, 7.4)

#### 4) Write a query to find hotels that offer both family rooms and non-smoking rooms

In [39]:
sql="SELECT Hotel,Family_rooms,Non_Smoking_Rooms FROM DataTable_2 WHERE Family_rooms='yes' AND Non_Smoking_Rooms='yes'"
result=cursor.execute(sql)
hotel=[]
family=[]
smoking=[]
for i in result:
    hotel.append(i[0])
    family.append(i[1])
    smoking.append(i[2])

In [40]:
DF=pd.DataFrame({"Hotel":hotel,"Family Room":family,"Non Smoking Room":smoking})
DF

,Hotel,Family Room,Non Smoking Room
0,Earls Court East Serviced Apartments,yes,yes
1,The Langham London,yes,yes
2,"Maldron Hotel Finsbury Park, London",yes,yes
3,Radisson Blu Edwardian New Providence Wharf Ho...,yes,yes
4,"Holiday Inn Express London Chingford, an IHG H...",yes,yes
...,...,...,...
1255,Pantages Hotel Toronto Centre,yes,yes
1256,The St. Regis Toronto,yes,yes
1257,Kensington Place Property,yes,yes
1258,Casa Queen Hotel,yes,yes
1259,Residence Inn by Marriott Toronto Downtown / E...,yes,yes

In [7]:
sql='DROP TABLE DataTable_3'
cursor.execute(sql)

In [8]:
# SQL query to retrieve table names
sql = "SELECT name FROM sqlite_master WHERE type='table';"

# Execute the query
cursor.execute(sql)

# Fetch and print the table names
tables = cursor.fetchall()
for table in tables:
    print(table[0])